### ISSUE TITLE
Add ntlk.download() to installation instructions

### ISSUE THREAD

**Issue by ghost** [gyachdav/awoiaf#10]
```
# python mineHousesDetails.py -s Tyrell
http://awoiaf.westeros.org/api.php?action=parse&redirects&prop=text&page=Tyrell&format=json
/usr/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
/Users/dmitriinechaev/01-personal/MD/TUM/2015-wintersemester/JSSeminar/awoiaf/Data/Houses/text/Tyrell
http://awoiaf.westeros.org/api.php?redirects&format=json&section=0&prop=text&action=parse&page=Tyrell
/Users/dmitriinechaev/01-personal/MD/TUM/2015-wintersemester/JSSeminar/awoiaf/Data/Houses/info/Tyrell
Traceback (most recent call last):
  File "/Users/dmitriinechaev/01-personal/MD/TUM/2015-wintersemester/JSSeminar/awoiaf/scr/lib/NLP.py", line 16, in pipeline
    tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
  File "/usr/local/lib/python2.7/site-packages/nltk/data.py", line 796, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python2.7/site-packages/nltk/data.py", line 914, in _open
    return find(path_, path + ['']).open()
  File "/usr/local/lib/python2.7/site-packages/nltk/data.py", line 636, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource u'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/Users/dmitriinechaev/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************
```

This issue is resolved by following instructions here:
http://www.nltk.org/data.html

I ran 
`# python -m nltk.downloader all`

But I did it just because I do not understand what data is required to run the utility. Do our users really need "all" option (which takes > 2GB data)? Will certain specific corpus be good enough?

**Comment by gyachdav** [comment]
Good point, but I haven't researched it really. Can you check?

**Comment by ghost** [comment]
I'll look into it.

**Comment by ghost** [comment]
It seems only `punkt` and `averaged_perceptron_tagger` are required. Adding to README.md now.
