### ISSUE TITLE
Must be sudo to run mineCharDetails.py

### ISSUE THREAD

**Issue by sacdallago** [gyachdav/awoiaf#5]
Stack trace:

```
chdallago@chdallagou:~/git/awoiaf/scr$ python mineCharDetails.py 
Traceback (most recent call last):
  File "/home/chdallago/git/awoiaf/scr/lib/Application.py", line 41, in __init__
    self.settings['rootdir'] = _config.get('Folders', 'rootdir')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'Folders'
Traceback (most recent call last):
  File "mineCharDetails.py", line 19, in <module>
    app = Application()
  File "/home/chdallago/git/awoiaf/scr/lib/Application.py", line 54, in __init__
    os.mkdir(_tmp_dir)
OSError: [Errno 13] Permission denied: '/Charachters'
```

**Comment by gyachdav** [comment]
It seems like the config file was not set and so the paths were messed up. I checked in a new version that guesses the installation folder and no longer needs the config file. Please try checking out the new revision and try again.

**Comment by ghost** [comment]
I haven't had this issue.
