### ISSUE TITLE
Cannot run mineHousesDetails.py, pageRank.py or mineCharDetails.py

### ISSUE THREAD

**Issue by sacdallago** [gyachdav/awoiaf#6]
Although my PYTHONPATH is:

```
chdallago@chdallagou:~/git/awoiaf/scr$ echo $PYTHONPATH
/home/chdallago/git/awoiaf/scr/lib
```

I get errors like:

```
chdallago@chdallagou:~/git/awoiaf/scr$ sudo python mineHousesDetails.py
Traceback (most recent call last):
  File "mineHousesDetails.py", line 14, in <module>
    from Houses import HousesPage
ImportError: No module named Houses
```

```
chdallago@chdallagou:~/git/awoiaf/scr$ sudo python pageRank.py 
Traceback (most recent call last):
  File "pageRank.py", line 6, in <module>
    from Charachters import Charachters

```

**Comment by gyachdav** [comment]
Try running without sudo (using sudo changes your env variables to the user you're trying to switch to). btw why are you trying to run using sudo in the first place?

**Comment by sacdallago** [comment]
Damn, how did I not think of that, that's totally right! Will check it out tomorrow.

I run as sudo because #5

**Comment by ghost** [comment]
I haven't had this problem.
